task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taska.urls')),
]

taska/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .import views

app_name = 'taska'
urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('', include('django.contrib.auth.urls')),
]

taska/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    due_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed = models.BooleanField(default=False)
    
    def __str__(self):
        return f'Title : {self.title} \nDescription : {self.description}'

taska/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                               widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']
        
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidateError("password don't match")
        return cd['password2']
    

taska/views.py
from django.shortcuts import render
from .forms import LoginForm, UserRegistrationForm
from .models import Task

# Create your views here.
def index(request):
    tasks = Task.objects.all()
    return render(request, 'taska/index.html', {'tasks':tasks})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password']
            )
            new_user.save()
            return render(request, 
                          'taska/register.html', {'new_user':new_user})
    else:
        user_form =UserRegistrationForm()
    return render(request, 'taska/register.html', {'user_form':user_form})

taska/templates/taska/base.html
<!doctype html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
         <li class="nav-item">
            <span class='navbar-text'>Hello, {{user.username}}</span>
        </li>
         <li class="nav-item">
            <a class='nav-link' href="{% url 'taska:logout' %}">Logout</a>
        </li>
        {% else %}
         <li class="nav-item">
            <a class='nav-link' href="{% url 'taska:login' %}">Login</a>
        </li>
         <li class="nav-item">
            <a  class='nav-link' href="{% url 'taska:register' %}">Register</a>
        </li>
        {% endif %}
    </ul>
    {% block content %}{% endblock content %}
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>

</body>
</html>

taska/templates/taska/index.html
{% extends "taska/base.html" %}
{% block title %}Welcome{% endblock title %}
{% block content %}
<div><dl>
    {% for task in tasks %}
    <dt>{{task.title}}</dt>
    <dd>{{task.description|truncatewords:30}}</dd>
    <dd>Due on {{task.due_date}}</dd>
    {% endfor %}
</dl>
</div>
{% endblock content %}

taska/templates/taska/register.html
{% extends "taska/base.html" %}
{% block title %}Create an account{% endblock title %}
{% block content %}
<h1>Create an account</h1>
<p>Please sign up using the following form</p>
<form method='post'>
    {{user_form.as_p}}
    {% csrf_token %}
    <p><input type='submit' value='Sign up'></p>
</form>
{% endblock content %}

taska/templates/taska/register_done.html
{% extends "taska/base.html" %}
{% block title %}Welcome{% endblock title %}
{% block content %}
<h1>Welcome {{new_user.first_name}} to Task manager</h1>
<p>
    Your account has been successful created.
Now you can<a href="{% url 'taska:login' %}">Login</a></p>
{% endblock content %}